spring.application.name=CadastroDeNinjas

# Configuração do H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=cadastro_db
spring.datasource.password=cadastro_db

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Configuração adicional importante
spring.datasource.generate-unique-name=false